source 'https://github.com/THEOplayer/CocoaPod-specs.git'

require_relative '../../Helpers/theolive-cocoapod-dependency'

target 'SwiftUI-example' do 
    pod 'THEOliveSDK', current_theolive_version
end