require_relative '../../Helpers/theolive-cocoapod-dependency'

target 'StoryboardExample-iOS' do
    platform :ios, '14.0'
    pod 'THEOliveSDK', current_theolive_version
end

target 'StoryboardExample-tvOS' do
    platform :tvos, '14.0'
    pod 'THEOliveSDK', current_theolive_version
end
